# Generated by Django 5.1.15 on 2026-08-19 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text='Qoder agent_xxx ID', max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(default='auto', max_length=32)),
                ('instructions', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('purpose', models.CharField(choices=[('general', '通用对话'), ('knowledge', '知识库问答'), ('task', '任务管理'), ('content', '内容处理'), ('code', '代码相关')], default='general', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent 配置',
                'verbose_name_plural': 'Agent 配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_id', models.CharField(help_text='Qoder env_xxx ID', max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Environment 配置',
                'verbose_name_plural': 'Environment 配置',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Qoder sess_xxx ID', max_length=64, unique=True)),
                ('environment_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('idle', '空闲'), ('processing', '处理中'), ('archived', '已归档')], default='idle', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='agents.agentconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session 记录',
                'verbose_name_plural': 'Session 记录',
                'ordering': ['-updated_at'],
            },
        ),
    ]
