# Generated by Django 5.1.15 on 2026-08-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionRecord',
        ),
    ]
