# Generated by Django 5.1.15 on 2026-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_delete_sessionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='purpose',
            field=models.CharField(choices=[('general', '通用对话'), ('knowledge', '知识库问答'), ('content', '内容处理'), ('code', '代码相关')], default='general', max_length=32),
        ),
    ]
