# Generated by Django 5.2.17 on 2026-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentconfig_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentconfig',
            name='system_prompt',
        ),
    ]
