# Generated by Django 5.1.15 on 2026-08-19 04:54

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='支持 Markdown 格式', verbose_name='正文')),
                ('source_file', models.FileField(blank=True, upload_to='knowledge/', verbose_name='源文件')),
                ('ai_summary', models.TextField(blank=True, help_text='AI 生成的摘要', verbose_name='AI 摘要')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.knowledgecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '知识文章',
                'verbose_name_plural': '知识文章',
                'ordering': ['-published_at'],
            },
        ),
    ]
