# Generated by Django 5.2.17 on 2026-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_article_knowledge_a_user_id_220c24_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='qmind_source_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='QMind 源 ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='qmind_sync_hash',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='QMind 同步指纹'),
        ),
    ]
