# Generated by Django 5.1.15 on 2026-08-25 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0009_activity_budget_alter_expense_category_and_more'),
        ('chat', '0002_message_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='提醒内容')),
                ('trigger_at', models.DateTimeField(db_index=True, verbose_name='触发时间')),
                ('status', models.CharField(choices=[('pending', '待触发'), ('fired', '已触发'), ('dismissed', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='activities.activity', verbose_name='关联活动')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='chat.message', verbose_name='来源对话消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
                'ordering': ['trigger_at'],
                'indexes': [models.Index(fields=['status', 'trigger_at'], name='core_remind_status_1235eb_idx'), models.Index(fields=['user', 'status'], name='core_remind_user_id_d50a99_idx')],
            },
        ),
    ]
