# Generated by Django 5.1.15 on 2026-08-27 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(verbose_name='摘要日期')),
                ('content', models.TextField(blank=True, default='', verbose_name='摘要内容')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='统计数据')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('ready', '已生成'), ('fallback', '降级生成')], default='pending', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日摘要',
                'verbose_name_plural': '每日摘要',
                'indexes': [models.Index(fields=['user', 'summary_date'], name='core_dailys_user_id_f0be25_idx')],
                'unique_together': {('user', 'summary_date')},
            },
        ),
    ]
