# Generated by Django 5.1.15 on 2026-08-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailysummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_date', models.DateField(verbose_name='洞察日期')),
                ('insights', models.JSONField(blank=True, default=list, verbose_name='洞察列表')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('ready', '已生成'), ('fallback', '降级生成')], default='pending', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日洞察',
                'verbose_name_plural': '每日洞察',
                'indexes': [models.Index(fields=['user', 'insight_date'], name='core_dailyi_user_id_5d0424_idx')],
                'unique_together': {('user', 'insight_date')},
            },
        ),
        migrations.CreateModel(
            name='SuggestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128, verbose_name='建议指纹')),
                ('action', models.CharField(choices=[('dismissed', '已关闭'), ('read', '已读')], default='dismissed', max_length=20, verbose_name='操作')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '建议状态',
                'verbose_name_plural': '建议状态',
                'indexes': [models.Index(fields=['user', 'action'], name='core_sugges_user_id_0472b6_idx')],
                'unique_together': {('user', 'fingerprint')},
            },
        ),
    ]
