# Generated by Django 5.2.17 on 2026-08-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyinsight_suggestionstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', '待触发'), ('fired', '已触发'), ('done', '已完成'), ('dismissed', '已忽略')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
