# Generated by Django 5.2.17 on 2026-09-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reminder_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySummary',
        ),
    ]
