# Generated by Django 5.2.17 on 2026-09-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_dailysummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='related_activity',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='source_message',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyInsight',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
