# Generated by Django 5.2.17 on 2026-09-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reminder_related_activity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestionState',
        ),
    ]
