# Generated by Django 5.2.17 on 2026-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_delete_suggestionstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('activity', '活动'), ('expense', '费用'), ('note', '备忘'), ('knowledge', '知识库')], db_index=True, max_length=20, verbose_name='用途')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['scope', 'sort', 'name'],
                'indexes': [models.Index(fields=['scope', 'is_active'], name='core_tag_scope_7ad54f_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'name'), name='uniq_tag_scope_name')],
            },
        ),
    ]
