# Generated by Django 5.2.17 on 2026-09-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['scope', 'sort', 'name'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
