# Generated by Django 5.2.17 on 2026-09-16 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tag_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='投递地址')),
                ('p256dh', models.CharField(max_length=100, verbose_name='加密公钥')),
                ('auth', models.CharField(max_length=100, verbose_name='认证密钥')),
                ('user_agent', models.CharField(blank=True, default='', max_length=200, verbose_name='设备标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='最近推送')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推送订阅',
                'verbose_name_plural': '推送订阅',
                'ordering': ['-created_at'],
            },
        ),
    ]
