# Generated by Django 5.2.17 on 2026-09-16 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_type', models.CharField(choices=[('daily_brief', '今日早报'), ('task_reminder', '任务提醒'), ('ai_summary', 'AI 任务总结')], max_length=20, verbose_name='内容类型')),
                ('time', models.TimeField(verbose_name='触发时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_sent_date', models.DateField(blank=True, help_text='幂等标记：同一天同一计划只发一次', null=True, verbose_name='最近发送日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推送计划',
                'verbose_name_plural': '推送计划',
                'ordering': ['time'],
                'constraints': [models.UniqueConstraint(fields=('user', 'push_type', 'time'), name='uniq_push_schedule_user_type_time')],
            },
        ),
    ]
