# Generated by Django 5.2.17 on 2026-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fts5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushschedule',
            name='push_type',
            field=models.CharField(choices=[('daily_brief', '今日早报'), ('task_reminder', '任务提醒'), ('ai_summary', 'AI 任务总结'), ('weekly_review', '每周回顾'), ('activity_reminder', '活动前提醒')], max_length=20, verbose_name='内容类型'),
        ),
    ]
