# Generated by Django 5.1.15 on 2026-08-21 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('action', models.CharField(choices=[('created', '创建了活动'), ('edited', '编辑了活动'), ('deleted', '删除了活动'), ('sub_created', '创建了子任务'), ('status_changed', '修改了状态')], max_length=20, verbose_name='操作类型')),
                ('summary', models.TextField(blank=True, verbose_name='变更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='activities.activity', verbose_name='关联活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '活动日志',
                'verbose_name_plural': '活动日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
