# Generated by Django 5.1.15 on 2026-08-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitylog'),
        ('chat', '0002_message_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to='chat.message', verbose_name='来源对话消息'),
        ),
    ]
