# Generated by Django 5.1.15 on 2026-08-25 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_cost_to_expense(apps, schema_editor):
    """将 Activity.cost > 0 的记录转为 Expense"""
    Activity = apps.get_model('activities', 'Activity')
    Expense = apps.get_model('activities', 'Expense')
    for activity in Activity.objects.filter(cost__gt=0):
        Expense.objects.create(
            activity=activity,
            user=activity.user,
            amount=activity.cost,
            category='other',
            note='从活动费用迁移',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_source_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('category', models.CharField(choices=[('transport', '交通'), ('accommodation', '住宿'), ('food', '餐饮'), ('ticket', '门票'), ('shopping', '购物'), ('work', '工作'), ('other', '其他')], default='other', max_length=20, verbose_name='类别')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='消费日期')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='activities.activity', verbose_name='关联活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='归属用户')),
            ],
            options={
                'verbose_name': '费用',
                'verbose_name_plural': '费用',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.RunPython(migrate_cost_to_expense, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='activity',
            name='cost',
        ),
    ]
