# Generated by Django 5.1.15 on 2026-08-25 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_expense_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('default_children', models.JSONField(blank=True, default=list, help_text='[{"name": "订票"}, {"name": "住宿"}]', verbose_name='预设子任务')),
                ('default_tags', models.JSONField(blank=True, default=list, verbose_name='预设标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动模板',
                'verbose_name_plural': '活动模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
