# Generated by Django 5.1.15 on 2026-08-25 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activitytemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity', verbose_name='关联活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='习惯名称')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=10, verbose_name='频率')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=周一...6=周日（仅每周时有效）', null=True, verbose_name='星期几')),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-28（仅每月时有效）', null=True, verbose_name='每月几号')),
                ('status', models.CharField(choices=[('planned', '计划'), ('in_progress', '进行中'), ('done', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='上次生成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '循环活动',
                'verbose_name_plural': '循环活动',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_activities', to='activities.recurringactivity', verbose_name='循环来源'),
        ),
    ]
