# Generated by Django 5.1.15 on 2026-08-25 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_attachment_recurringactivity_and_more'),
        ('chat', '0002_message_payload'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算上限'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('transport', '交通'), ('accommodation', '住宿'), ('food', '餐饮'), ('ticket', '门票'), ('shopping', '购物'), ('work', '工作'), ('digital', '数码'), ('health', '健康'), ('other', '其他')], default='other', max_length=20, verbose_name='类别'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'status'], name='activities__user_id_505b87_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-start_date'], name='activities__user_id_256241_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category', '-paid_at'], name='activities__user_id_a1454e_idx'),
        ),
    ]
