# Generated by Django 5.1.15 on 2026-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_budget_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时（分钟）'),
        ),
    ]
