# Generated by Django 5.2.17 on 2026-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringactivity',
            name='status',
        ),
    ]
