# Generated by Django 5.2.17 on 2026-09-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_remove_recurringactivity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='recurring_source',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='source_message',
        ),
    ]
