# Generated by Django 5.2.17 on 2026-09-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_remove_activity_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityTemplate',
        ),
        migrations.DeleteModel(
            name='RecurringActivity',
        ),
    ]
