# Generated by Django 5.2.17 on 2026-09-09 07:10

from django.db import migrations, models

# 初始类别 = 原 Expense.CATEGORY_CHOICES 的 9 项。字面量写死在迁移里
# （迁移必须自包含，不能 import models——models 上的定义会随后续改动漂移）。
# sort 顺序沿用原 choices 声明顺序（表单下拉/建议的默认展示顺序）。
INITIAL_CATEGORIES = [
    ('transport', '交通', 10),
    ('accommodation', '住宿', 20),
    ('food', '餐饮', 30),
    ('ticket', '门票', 40),
    ('shopping', '购物', 50),
    ('work', '工作', 60),
    ('digital', '数码', 70),
    ('health', '健康', 80),
    ('other', '其他', 90),
]


def seed_categories(apps, schema_editor):
    """把原硬编码的 9 类灌入 ExpenseCategory 表（幂等：按 key 去重）"""
    ExpenseCategory = apps.get_model('activities', 'ExpenseCategory')
    existing = set(ExpenseCategory.objects.values_list('key', flat=True))
    for key, label, sort in INITIAL_CATEGORIES:
        if key not in existing:
            ExpenseCategory.objects.create(key=key, label=label, sort=sort,
                                           is_active=True)


def unseed_categories(apps, schema_editor):
    """回滚：只删本次灌入的初始类别；类别表被删后 Expense.category 仍存
    原字符串 key，历史数据可读（display 回落 key），不丢不炸"""
    ExpenseCategory = apps.get_model('activities', 'ExpenseCategory')
    ExpenseCategory.objects.filter(
        key__in=[c[0] for c in INITIAL_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_remove_recurringactivity_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='标识')),
                ('label', models.CharField(max_length=20, verbose_name='显示名')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '费用类别',
                'verbose_name_plural': '费用类别',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='other', max_length=20, verbose_name='类别'),
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
