# Generated by Django 5.2.17 on 2026-09-09 14:04
#
# 费用「分类」体系整体下线，统一并入标签体系（core.Tag，scope='expense'）：
# 1. RunPython：ExpenseCategory.label → core.Tag(scope='expense')（同名复用），
#    存量 Expense.category key 反查 label 后挂到 Expense.tags（已挂过去重）；
# 2. RemoveField/DeleteModel：删 category 字段、索引与 ExpenseCategory 表。
#    数据搬迁必须排在 RemoveField 之前（反查依赖旧列）。
# 不可逆（Reverse 为 noop）：历史归类已完整落到 tags，无回滚价值。

from django.conf import settings
from django.db import migrations, models


def migrate_category_to_tags(apps, schema_editor):
    Tag = apps.get_model('core', 'Tag')
    Expense = apps.get_model('activities', 'Expense')
    ExpenseCategory = apps.get_model('activities', 'ExpenseCategory')

    # label → Tag(scope='expense')，同名标签已存在则复用（get_or_create 口径与
    # core.tags.ensure_tags 一致；is_active/sort 走模型默认值）
    tag_by_label = {}
    for cat in ExpenseCategory.objects.all():
        tag, _created = Tag.objects.get_or_create(
            scope='expense', name=cat.label,
            defaults={'is_active': True, 'sort': 100},
        )
        tag_by_label[cat.key] = tag

    # key 反查 label → 挂标签，去重（已挂过不重复加）
    for exp in Expense.objects.exclude(category='').iterator():
        tag = tag_by_label.get(exp.category)
        if tag is not None and not exp.tags.filter(pk=tag.pk).exists():
            exp.tags.add(tag)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_migrate_taggit_data'),
        ('core', '0009_alter_tag_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_category_to_tags, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='expense',
            name='activities__user_id_a1454e_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-paid_at'], name='activities__user_id_133e3b_idx'),
        ),
    ]
