# Generated by Django 5.2.17 on 2026-09-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_alter_activitylog_action_activitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
