# Generated by Django 5.2.17 on 2026-09-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_activity_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocking', to='activities.activity', verbose_name='前置依赖'),
        ),
    ]
