# Generated by Django 5.2.17 on 2026-09-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_add_blocked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('default_tags', models.CharField(blank=True, help_text='逗号分隔', max_length=255, verbose_name='默认标签')),
                ('default_participants', models.CharField(blank=True, help_text='逗号分隔', max_length=255, verbose_name='默认参与者')),
                ('default_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='默认预算')),
                ('default_description', models.TextField(blank=True, verbose_name='默认描述')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动模板',
                'verbose_name_plural': '活动模板',
                'ordering': ['-use_count', '-created_at'],
            },
        ),
    ]
