# Generated by Django 5.2.17 on 2026-09-18 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_add_activity_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('suggestion', models.TextField(blank=True, verbose_name='建议内容')),
                ('is_ai', models.BooleanField(default=True, verbose_name='是否 AI 生成')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日建议',
                'verbose_name_plural': '每日建议',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
