# Generated by Django 5.2.17 on 2026-09-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_add_daily_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
    ]
