# Generated by Django 5.1.15 on 2026-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, help_text='结构化卡片协议：{"card": "activity|activity_list|...", "activity_ids": [...], "action": {...}}', null=True),
        ),
    ]
