# Generated by Django 5.2.17 on 2026-09-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='turn_idle_at',
            field=models.DateTimeField(blank=True, help_text='首次观察到“已 idle 但无本轮文本”的时刻，宽限期判定用', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='turn_message',
            field=models.ForeignKey(blank=True, help_text='本轮待回答的那条用户消息（不靠「取最后一条 user」推导：异步后用户可以在等回复时接着打字，推导会配错对象）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='turn_prompt',
            field=models.TextField(blank=True, help_text='实际发给 Qoder 的完整文本（页面上下文 + 知识库注入 + 用户原文）。必须存：把它塞进用户消息会污染历史（现有约定只存原文），不存则无法重试发送（首帧协议还在跑时发第二条会撞 409）'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='turn_started_at',
            field=models.DateTimeField(blank=True, help_text='本轮开始时间，TTL 超时判定用', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='turn_state',
            field=models.CharField(choices=[('none', '无'), ('queued', '待发送'), ('awaiting', '等待回复'), ('finalizing', '收尾中'), ('done', '已完成'), ('error', '已中断')], default='none', help_text='当前轮次状态（异步收发状态机，刷新页面能续上全靠它）', max_length=20),
        ),
    ]
