# Generated by Django 5.2.17 on 2026-09-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_remove_recurringactivity_status'),
        ('chat', '0003_conversation_turn_idle_at_conversation_turn_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pin_activity',
            field=models.ForeignKey(blank=True, help_text='@ 钉选的活动（会话级，不是单条消息级）：钉上后每一轮都自动带上它的结构化现状，用户不必反复说对象名。存 FK 而不是裸 id：活动被删要自动失效；Message.payload 里那种裸 id 是给一次性卡片用的，不是长期状态。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activity'),
        ),
    ]
