# Generated by Django 5.2.17 on 2026-09-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_pin_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_daily',
            field=models.BooleanField(default=False, help_text='常驻会话标记（每用户最多一个）：系统自动创建维护，归档会被复活，删除后下次访问自动重建。'),
        ),
    ]
