# Generated by Django 5.2.17 on 2026-09-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_is_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_daily',
        ),
    ]
