# Generated by Django 5.2.17 on 2026-09-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_conversation_is_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='turn_retries',
            field=models.PositiveSmallIntegerField(default=0, help_text='本轮已用的自动重试次数（发送失败/超时/空回复时自动重发同一份 turn_prompt，上限 chat.models.TURN_MAX_RETRIES）。新发送时清零'),
        ),
    ]
