# Generated by Django 5.1.15 on 2026-08-27 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_message_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='记忆内容')),
                ('category', models.CharField(choices=[('preference', '偏好'), ('fact', '事实'), ('goal', '目标'), ('relationship', '关系'), ('habit', '习惯'), ('other', '其他')], default='other', max_length=20, verbose_name='类别')),
                ('importance', models.IntegerField(default=5, verbose_name='重要度')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='上次访问')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='chat.message', verbose_name='来源消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '记忆',
                'verbose_name_plural': '记忆',
                'ordering': ['-importance', '-updated_at'],
                'indexes': [models.Index(fields=['user', '-importance'], name='memory_memo_user_id_5a7fac_idx'), models.Index(fields=['user', 'category'], name='memory_memo_user_id_c9dd68_idx')],
            },
        ),
    ]
