# Generated by Django 5.2.17 on 2026-09-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='consolidated',
            field=models.BooleanField(default=False, help_text='该条记忆已被 consolidate_memories 命令合成为画像，检索时跳过', verbose_name='已被聚合'),
        ),
    ]
